# Generated by Django 5.0.6 on 2024-07-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
